=== shulanztf/mavApiSerNoDB/src/main/resources/my-stud.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT classrooms (classroom+)>
<!ELEMENT classroom (grade,classname,students)>
<!ATTLIST classroom id  ID #REQUIRED>
<!ELEMENT classname (#PCDATA)>
<!ELEMENT grade (#PCDATA)>

<!ELEMENT students (student+)>
<!ELEMENT student (id,abc,studentname)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT studentname (#PCDATA)>
<!ELEMENT abc (#PCDATA)>

=== shulanztf/mavApiSerNoDB/src/main/resources/dtdstud.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classrooms SYSTEM "my-stud.dtd">
<classrooms>
	<classroom id="">
		<students>
			<student>
				<abc></abc>
				<age></age>
				<id></id>
				<studentname></studentname>
			</student>
		</students>
	</classroom>
</classrooms>
